
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frame2 extends javax.swing.JFrame {
  String str, str1; 
  int choice,z,pin=1234,counter = 0,a = 3; 
  int t,s,tab = 50000; 

    public frame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setor = new javax.swing.JButton();
        bantuan = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        tarik = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Lakukan Transaksi");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 110, 30);

        jLabel2.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Penyetoran");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 100, 70, 20);

        jLabel3.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Bantuan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 150, 60, 20);

        jLabel4.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Exit");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 200, 50, 20);

        jLabel5.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Informasi Saldo");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 100, 90, 30);

        jLabel6.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("Transfer");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(200, 150, 60, 20);

        jLabel7.setFont(new java.awt.Font("Shruti", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 51));
        jLabel7.setText("Penarikan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(200, 200, 60, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(70, 10, 260, 280);

        setor.setText("<");
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor);
        setor.setBounds(20, 110, 50, 30);

        bantuan.setText("<");
        bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bantuanActionPerformed(evt);
            }
        });
        getContentPane().add(bantuan);
        bantuan.setBounds(20, 160, 50, 30);

        exit.setText("<");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(20, 210, 50, 30);

        saldo.setText(">");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        getContentPane().add(saldo);
        saldo.setBounds(330, 110, 50, 30);

        transfer.setText(">");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        getContentPane().add(transfer);
        transfer.setBounds(330, 160, 50, 30);

        tarik.setText(">");
        tarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarikActionPerformed(evt);
            }
        });
        getContentPane().add(tarik);
        tarik.setBounds(330, 210, 50, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Smktelkom\\Downloads\\hd-backgrounds-16.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-6, -10, 410, 310);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void tarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarikActionPerformed
    str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penarikan : " ); //pengambilan 
    t = Integer.parseInt(str1); 
    tarik mengambil = new tarik(); 
    mengambil.ambil(tab,t); 
    tab = mengambil.getsaldo(); 
    }//GEN-LAST:event_tarikActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    JOptionPane.showMessageDialog(null,"Terimakasih telah menggunakan ATM BCA - MALANG, silahkan ambil kartu ATM Anda."); 
    System.exit(0); 
    }//GEN-LAST:event_exitActionPerformed

    private void bantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bantuanActionPerformed
    JOptionPane.showMessageDialog(null,"Cara Penggunaan Aplikasi\n[1] Masukkan PIN dengan benar\n[2] Bertransaksilah dengan benar sesuai pilihan\n[3] Gunakan uang sesuai kebutuhan dan rajinlah menabung\n ","INFO",1); 
    }//GEN-LAST:event_bantuanActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
    JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : " +tab);
    }//GEN-LAST:event_saldoActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
    str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah penyetoran: " ); //menabung 
    s = Integer.parseInt(str1); 
    setor hasil = new setor(); 
    hasil.menabung(tab, s); 
    tab =hasil.getsaldo(); 
    }//GEN-LAST:event_setorActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
    str1 = JOptionPane.showInputDialog(null,"Masukkan nomor rekening tujuan : " ); //transfer 
    str1 = JOptionPane.showInputDialog(null,"Masukkan jumlah transfer : ");
    t = Integer.parseInt(str1); 
    transfer mengambil = new transfer(); 
    mengambil.ambil(tab,t); 
    tab = mengambil.getsaldo(); 
    }//GEN-LAST:event_transferActionPerformed

    class setor {
    private int saldo;
    public void menabung (int bal, int s) {
        if (s%100!=0)
            JOptionPane.showMessageDialog(null,
                    "Mesin ATM BRI tidak menerima uang koin \nSilahkan ulangi kembali",
                    "Transaksi Gagal",0);
        else if (s<50000)
            JOptionPane.showMessageDialog(null,
                    "Besaran minimal setor tunai adalah Rp 50000,00","ERROR",0);
        else if (s>=50000) {
            saldo = bal+s;
            JOptionPane.showMessageDialog(null,
                    "Saldo Anda saat ini sebesar : " + saldo);
        }
    }
   public int getsaldo() {
       return saldo;
   } 
}
    class transfer {
    private int saldo;
    public void ambil (int tab, int t) {
       
            if (t<tab)
                JOptionPane.showMessageDialog(null,"Saldo Anda tidak mencukupi"
                        + "\nSilahkan lakukan penyetoran","Transaksi gagal",0);
            else {
                saldo = tab-t;
                JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : "
                +saldo);
                 if (tab<=50000)
                JOptionPane.showMessageDialog(null,"Saldo minimal harus Rp 50000,00,"
                    + "Segera lakukan penyetoran unuk menghindari penutupan akun."
                    + "","CAUTION",2);
    }
}
    
public int getsaldo() {
return saldo;
}
    }

    class tarik {
    private int saldo;
    public void ambil (int tab, int t) {
        if (t%100!=0)
            JOptionPane.showMessageDialog(null,"Mesin ATM BRI tidak menerima uang koin"
                    + "\nSilahkan ulangi lagi","Transaksi Gagal",0);
        else {
            if (t<tab)
                JOptionPane.showMessageDialog(null,"Saldo Anda tidak mencukupi"
                        + "\nSilahkan lakukan penyetoran","Transaksi gagal",0);
            else if (t<50000)
                JOptionPane.showMessageDialog(null,"Besaran minimal pengambilan tunai"
                        + "adalah Rp 50000","Transaksi Gagal",0);
            else {
                saldo = tab-t;
                JOptionPane.showMessageDialog(null,"Saldo Anda saat ini sebesar : "
                +saldo);
            if (tab<=50000)
                JOptionPane.showMessageDialog(null,"Saldo minimal harus Rp 50000,00,"
                    + "Segera lakukan penyetoran unuk menghindari penutupan akun."
                    + "","CAUTION",2);
    }
}
    }
public int getsaldo() {
return saldo;
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bantuan;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saldo;
    private javax.swing.JButton setor;
    private javax.swing.JButton tarik;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
